sensor:
  - name: Ventilatieniveau zone 5
    address: 2208
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: 42209 inschakelen/uitschakelen
    address: 2209
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: Stroomvraag (flow) zone 5
    address: 2218
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: 42219 inschakelen/uitschakelen
    address: 2219
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: Ongebalanceerde stroomvraag zone 5
    address: 3204
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}