sensor:
  - name: Positie stepper zoneklep 4
    address: 2040
    unit_of_measurement: Stappen
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: 42041 inschakelen/uitschakelen
    address: 2041
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: Ventilatieniveau zone 4
    address: 2206
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: 42207 inschakelen/uitschakelen
    address: 2207
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: Stroomvraag (flow) zone 4
    address: 2216
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: 42217 inschakelen/uitschakelen
    address: 2217
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: Ongebalanceerde stroomvraag zone 4
    address: 3203
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}