sensor:
  - name: Fabrikantgroep
    address: 10
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Sub-ID van de fabrikant
    address: 11
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: ProductNoneID
    address: 12
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Softwareversie
    address: 13
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Softwarerevisie
    address: 14
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Lijstversie
    address: 15
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: OEM-code
    address: 16
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Serienummer deel 1 (uint 64) (MSB)
    address: 100
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Serienummer deel 2 (uint 64)
    address: 101
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Serienummer deel 3 (uint 64)
    address: 102
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
  - name: Serienummer deel 4 (uint 64) (LSB)
    address: 103
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}

number:
  # Changing these will also make you change your yaml files: 
  - name: Modbus-addres
    address: 0
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 1
    max_value: 247
    step: 1
  - name: Baud rate
    address: 1
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 4
    step: 1
  - name: Pariteit
    address: 2
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 2
    step: 1