switch:
  - platform: template
    name: "Bypass valve - on/off" # 0 = auto 1 = Manual
    id: HRU_bypass_valve_on_off_switch
    icon: mdi:toggle-switch-variant
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if (id(HRU_bypass_valve_on_off).state == 1) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      then:
        if:
          condition:
            lambda: 'return id(hru_m3h_toevoer_binnen_total).state > 200;'
          then: 
            - logger.log: "The sensor value is above 200!, change fan to 200"
            - number.set:
                id: HRU_fan_demand_value
                value: 200 # Lower the fan to the bypass allowed value
            - delay: 5s # Give fan spindown time
            - number.set:
                id: HRU_bypass_valve_on_off
                value: 1 # Set the bypass to on.
            - delay: 5s # Give bypass valve time to open
            - number.set:
                id: HRU_fan_demand_value
                value: 0 # Set the fan back to auto.
          else:
            - logger.log: "The sensor value is below 200!, turn on bypass"
            - number.set:
                id: HRU_bypass_valve_on_off
                value: 1 # Set the bypass to on.
    turn_off_action:
      then:
        if:
          condition:
            lambda: 'return id(hru_m3h_toevoer_binnen_total).state > 200;'
          then: 
            - logger.log: "The sensor value is above 200, change fan to 200 before turn off"
            - number.set:
                id: HRU_fan_demand_value
                value: 200 # Lower the fan to the bypass allowed value
            - delay: 5s # Give fan spindown time
            - number.set:
                id: HRU_bypass_valve_on_off
                value: 0 # Set the bypass to off.
            - delay: 5s # Give bypass valve time to open
            - number.set:
                id: HRU_fan_demand_value
                value: 0 # Set the fan back to auto.
          else:
            - logger.log: "The sensor value is below 200, turn off bypass"
            - number.set:
                id: HRU_bypass_valve_on_off
                value: 0 # Set the bypass to off.