###
# Select Manual / Auto mode on the WTW Unit

# These are technically duplicates from the sensors_general.yaml,
# But are a switch instead.
select:
  - name: ${sl_2011}
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    id: HRU_fan_demand_ingress_select 
    address: 2011
    optionsmap:
      Auto: 0
      Manual: 1
    entity_category: config
    use_write_multiple: true
    icon: mdi:toggle-switch-variant
  - name: ${sl_2021}
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    id: HRU_fan_flow_ingress_select
    address: 2021
    optionsmap:
      Auto: 0
      Manual: 1
    entity_category: config
    use_write_multiple: true
    icon: mdi:toggle-switch-variant
  - name: ${sl_499}
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    id: HRU_fan_flow_ingress_select
    address: 499
    optionsmap:
      Running: 0
      Restart: 1
    entity_category: config
    use_write_multiple: true
    icon: mdi:toggle-switch-variant