sensor:
  - name: ${499}
    address: 499
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: ${2000}
    address: 2000
    value_type: U_WORD
    min_value: 0
    max_value: 25
    step: 1
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${2001}
    address: 2001
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  # Demand ventialtion: (ingress)
  - name: ${2010}
    address: 2010
    min_value: 0
    max_value: ${max_cap}
    step: 1
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${2011}
    address: 2011
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  # Demand ventialtion: (exhaust)
  - name: Ventilatievraag afvoer
    address: ${2012}
    unit_of_measurement: m3/h
    value_type: U_WORD
    min_value: 0
    max_value: ${max_cap}
    step: 1
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${2013}
    address: 2013
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  # massflow intake
  - name: ${2020}
    address: 2020
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${2021}
    address: 2021
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  # massflow exhaust
  - name: ${2022}
    address: 2022
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${2023}
    address: 2023
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  # Frost valve
  - name: ${2030}
    address: 2030
    unit_of_measurement: Stappen
    min_value: 0
    max_value: 510
    step: 1
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${2031}
    address: 2031
    min_value: 0
    max_value: 1
    step: 1
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  # Bypass valve
  - name: ${2032}
    address: 2032
    unit_of_measurement: Stappen
    value_type: U_WORD
    min_value: 0
    max_value: ${flap_max}
    step: ${flap_max}
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${2033}
    address: 2033
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3000}
    address: 3000
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3001}
    address: 3001
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3010}
    address: 3010
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3011}
    address: 3011
    unit_of_measurement: Ppm
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3020}
    address: 3020
    unit_of_measurement: Rpm
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3021}
    address: 3021
    unit_of_measurement: Rpm
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3022}
    address: 3022
    unit_of_measurement: W
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3023}
    address: 3023
    unit_of_measurement: W
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3024}
    address: 3024
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3030}
    address: 3030
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3031}
    address: 3031
    unit_of_measurement: kg/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3032}
    address: 3032
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3033}
    address: 3033
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3040}
    address: 3040
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3050}
    address: 3050
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3051}
    address: 3051
    unit_of_measurement: kg/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3052}
    address: 3052
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3053}
    address: 3053
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3060}
    id: hru_m3h_toevoer_binnen_total
    address: 3060
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3061}
    address: 3061
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3062}
    address: 3062
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3063}
    address: 3063
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3070}
    address: 3070
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3071}
    address: 3071
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3072}
    address: 3072
    unit_of_measurement: °C
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3073}
    address: 3073
    unit_of_measurement: '%'
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3080}
    address: 3080
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3081}
    address: 3081
    unit_of_measurement: "kg/h"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3082}
    address: 3082
    filters:
    - multiply: 0.1
    unit_of_measurement: "°C"
    value_type: S_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${3083}
    address: 3083
    unit_of_measurement: "%"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    device_class: "humidity"
  - name: ${3200}
    address: 3200
    unit_of_measurement: "m3/h"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${4000}
    address: 4000
    unit_of_measurement: "h"
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
  - name: ${4001}
    address: 4001
    unit_of_measurement: "h"
    value_type: U_WORD
    register_type: holding
    state_class: "total_increasing"
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates}
  - name: ${4002}
    address: 4002
    unit_of_measurement: "m3"
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates}
    state_class: "total_increasing"
  - name: ${4003}
    address: 4003
    unit_of_measurement: "m3"
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates}
    state_class: "total_increasing"