# If you have more than 1 zone in the WTW unit enalbe this file
sensor:
  - name: Positie stepper zoneklep 2
    address: 2036
    unit_of_measurement: Stappen
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42037 inschakelen/uitschakelen
    address: 2037
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Positie stepperzoneklep 3
    address: 2038
    unit_of_measurement: Stappen
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42039 inschakelen/uitschakelen
    address: 2039
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Positie stepper zoneklep 4
    address: 2040
    unit_of_measurement: Stappen
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42041 inschakelen/uitschakelen
    address: 2041
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ventilatieniveau zone 2
    address: 2202
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42203 inschakelen/uitschakelen
    address: 2203
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ventilatieniveau zone 3
    address: 2204
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42205 inschakelen/uitschakelen
    address: 2205
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ventilatieniveau zone 4
    address: 2206
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42207 inschakelen/uitschakelen
    address: 2207
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ventilatieniveau zone 5
    address: 2208
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42209 inschakelen/uitschakelen
    address: 2209
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Stroomvraag (flow) zone 2
    address: 2212
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42213 inschakelen/uitschakelen
    address: 2213
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Stroomvraag (flow) zone 3
    address: 2214
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42215 inschakelen/uitschakelen
    address: 2215
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Stroomvraag (flow) zone 4
    address: 2216
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42217 inschakelen/uitschakelen
    address: 2217
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Stroomvraag (flow) zone 5
    address: 2218
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: 42219 inschakelen/uitschakelen
    address: 2219
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ongebalanceerde stroomvraag zone 2
    address: 3201
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ongebalanceerde stroomvraag zone 3
    address: 3202
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ongebalanceerde stroomvraag zone 4
    address: 3203
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw
  - name: Ongebalanceerde stroomvraag zone 5
    address: 3204
    unit_of_measurement: m³/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: wtw